# Generated by Django 3.0.2 on 2020-01-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('W', 'World'), ('C', 'Country'), ('T', 'Technology'), ('B', 'Business'), ('SC', 'Science'), ('E', 'Entertainment'), ('S', 'Sports'), ('H', 'Health')], default='W', max_length=2)),
                ('url', models.URLField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField()),
                ('visit_to', models.CharField(choices=[('W', 'World'), ('C', 'Country'), ('T', 'Technology'), ('B', 'Business'), ('SC', 'Science'), ('E', 'Entertainment'), ('S', 'Sports'), ('H', 'Health')], default='W', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.TextField()),
                ('image', models.TextField()),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
            ],
        ),
    ]
