# Generated by Django 2.2.4 on 2020-01-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='link',
            field=models.TextField(),
        ),
    ]
